import React,{useEffect,useMemo,useState}from"react";
import{BarChart3,Building2,CalendarClock,ChevronLeft,Clock3,Download,FileSearch,GraduationCap,Printer,Search,SlidersHorizontal,Sparkles,UserRound}from"lucide-react";
import{Badge,EmptyState,Field,MetaPill,Notice,PageTitle,PrimaryButton,RecordCard,RecordDeck,SecondaryButton,Surface}from"./ui";
import{AdCollege,AdCourse,AdInstructor,AdSection,AdTerm,FSchedule}from"../types";
import{runVisualTransition}from"../utils/visualTransition";
import{coerceScopeValues,resolveScopeSelection}from"../utils/scopeContext";
export type ReportMode="searchInstructor"|"searchRoom"|"searchTime"|"searchRoomTime"|"searchAdvanced"|"reportDepartment"|"reportInstructor"|"reportRoom"|"reportTime"|"reportRoomTime";
type PrintKind="DepartmentSchedule"|"ListofTeacherCourse"|"InstructorWithRoom"|"TeacherWithCourse"|"InstructorReport2"|"WeekWithInstructor"|"RoomReport2"|"WeekWithInstructorByDept"|"TimeReport2"|"RoomTimeReport2"|null;
interface Props{mode:ReportMode;user?:{SystemUserId:number;IsAdminUser?:boolean};scopes?:any[];availableModes?:ReportMode[]}
interface Filters{collegeId:number;sectionId:number;termId:number;instructorId:number;civil:string;building:string;hall:string;courseId:number;courseCode:string;sectionCode:string;startTime:string;endTime:string;sun:boolean;mon:boolean;tue:boolean;wed:boolean;thr:boolean}
const fresh=():Filters=>({collegeId:0,sectionId:0,termId:0,instructorId:0,civil:"",building:"",hall:"",courseId:0,courseCode:"",sectionCode:"",startTime:"",endTime:"",sun:false,mon:false,tue:false,wed:false,thr:false});
const config:Record<ReportMode,{title:string;short:string;kind:"search"|"report";icon:React.ReactNode}>={
 searchInstructor:{title:"حسب أستاذ المقرر",short:"أستاذ",kind:"search",icon:<UserRound/>},searchRoom:{title:"حسب المبنى والقاعة",short:"قاعة",kind:"search",icon:<Building2/>},searchTime:{title:"حسب الوقت",short:"وقت",kind:"search",icon:<Clock3/>},searchRoomTime:{title:"القاعة والوقت معاً",short:"قاعة + وقت",kind:"search",icon:<CalendarClock/>},searchAdvanced:{title:"استعلام شامل",short:"شامل",kind:"search",icon:<Sparkles/>},
 reportDepartment:{title:"القسم العلمي الشامل",short:"القسم",kind:"report",icon:<GraduationCap/>},reportInstructor:{title:"الأستاذ والمزاولة",short:"الأستاذ",kind:"report",icon:<UserRound/>},reportRoom:{title:"المباني والقاعات",short:"القاعات",kind:"report",icon:<Building2/>},reportTime:{title:"الأوقات",short:"الأوقات",kind:"report",icon:<Clock3/>},reportRoomTime:{title:"الوقت والقاعات",short:"وقت + قاعة",kind:"report",icon:<CalendarClock/>}
};
const dayText=(s:FSchedule)=>s.fdetail||[s.fsunday&&"الأحد",s.fmonday&&"الاثنين",s.ftuesday&&"الثلاثاء",s.fwednesday&&"الأربعاء",s.fthursday&&"الخميس"].filter(Boolean).join(" - ");
export default function Reports({mode,user,scopes=[],availableModes}:Props){
 const prefKey=`schedule-unified-prefs-${user?.SystemUserId||0}`;let saved:any={};try{saved=JSON.parse(localStorage.getItem(prefKey)||"{}")}catch{}
 const allowed=(availableModes?.length?availableModes:[mode]);
 const initialMode=(allowed.includes(saved.mode)?saved.mode:mode) as ReportMode;
 const[activeMode,setActiveMode]=useState<ReportMode>(initialMode),[colleges,setColleges]=useState<AdCollege[]>([]),[sections,setSections]=useState<AdSection[]>([]),[terms,setTerms]=useState<AdTerm[]>([]),[instructors,setInstructors]=useState<AdInstructor[]>([]),[courses,setCourses]=useState<AdCourse[]>([]),[all,setAll]=useState<FSchedule[]>([]),[filters,setFilters]=useState<Filters>(()=>({...fresh(),...(saved.filters||{})})),[results,setResults]=useState<FSchedule[]>([]),[searched,setSearched]=useState(false),[printKind,setPrintKind]=useState<PrintKind>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[visibleLimit,setVisibleLimit]=useState(120),[reportFocus,setReportFocus]=useState<{kind:"instructor"|"room";value:string;label:string}|null>(null);
 const info=config[activeMode],kind=info.kind,isPowerAdmin=Boolean(user?.IsAdminUser||user?.SystemUserId===1);
 useEffect(()=>{if(!allowed.includes(activeMode))setActiveMode(mode)},[mode,allowed.join("|")]);
 useEffect(()=>{localStorage.setItem(prefKey,JSON.stringify({mode:activeMode,filters:{collegeId:filters.collegeId,sectionId:filters.sectionId,termId:filters.termId,building:filters.building,hall:filters.hall}}))},[activeMode,filters.collegeId,filters.sectionId,filters.termId,filters.building,filters.hall]);
 useEffect(()=>{(async()=>{setLoading(true);try{const rs=await Promise.all(["colleges","sections","terms","instructors","courses"].map(x=>fetch(`/api/${x}`)));if(rs.some(r=>!r.ok))throw new Error("تعذر تحميل البيانات");const d=await Promise.all(rs.map(r=>r.json()));const sortedTerms=[...d[2]].sort((a:AdTerm,b:AdTerm)=>Number(b.AdTermId)-Number(a.AdTermId));setColleges(d[0]);setSections(d[1]);setTerms(sortedTerms);setInstructors(d[3]);setCourses(d[4]);const latestTermId=Number(sortedTerms[0]?.AdTermId||0);let collegeId=Number(saved?.filters?.collegeId||0),sectionId=Number(saved?.filters?.sectionId||0);if(isPowerAdmin){if(!collegeId||!d[0].some((c:AdCollege)=>c.AdCollegeId===collegeId))collegeId=Number(d[1][0]?.AdCollegeId||d[0][0]?.AdCollegeId||0);if(!sectionId||d[1].find((sec:AdSection)=>sec.AdSectionId===sectionId)?.AdCollegeId!==collegeId)sectionId=Number(d[1].find((sec:AdSection)=>sec.AdCollegeId===collegeId)?.AdSectionId||0)}else{const scoped=coerceScopeValues(scopes,collegeId,sectionId,false);collegeId=scoped.collegeId;sectionId=scoped.sectionId}setFilters(prev=>({...prev,collegeId,sectionId,termId:latestTermId}))}catch(e:any){setError(e.message)}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!filters.termId)return;const controller=new AbortController();const q=new URLSearchParams({termId:String(filters.termId)});if(filters.collegeId)q.set("collegeId",String(filters.collegeId));if(filters.sectionId)q.set("sectionId",String(filters.sectionId));(async()=>{try{const r=await fetch(`/api/schedules?${q}`,{signal:controller.signal});if(!r.ok)throw new Error("تعذر تحميل مواعيد النطاق الحالي");setAll(await r.json())}catch(e:any){if(e?.name!=="AbortError")setError(e.message)}})();return()=>controller.abort()},[filters.collegeId,filters.sectionId,filters.termId]);
 useEffect(()=>{if(!sections.length||isPowerAdmin)return;setFilters(prev=>{const next=coerceScopeValues(scopes,prev.collegeId,prev.sectionId,false);if(next.collegeId===prev.collegeId&&next.sectionId===prev.sectionId)return prev;return{...prev,collegeId:next.collegeId,sectionId:next.sectionId}})},[sections.length,scopes,isPowerAdmin]);
 const scopeState=resolveScopeSelection(scopes,filters.collegeId,isPowerAdmin);
 const sectionOptions=sections.filter(s=>!filters.collegeId||s.AdCollegeId===filters.collegeId),courseOptions=courses.filter(c=>!filters.sectionId||c.AdSectionId===filters.sectionId);
 const buildings=useMemo(()=>Array.from(new Set(all.filter(s=>(!filters.sectionId||s.AdSectionId===filters.sectionId)&&(!filters.termId||s.AdTermId===filters.termId)).map(s=>s.AdRoomCode).filter(Boolean))).sort(),[all,filters.sectionId,filters.termId]);
 const halls=useMemo(()=>Array.from(new Set(all.filter(s=>(!filters.building||s.AdRoomCode===filters.building)&&(!filters.termId||s.AdTermId===filters.termId)).map(s=>s.AdRoomHall).filter(Boolean))).sort(),[all,filters.building,filters.termId]);
 const instructorById=useMemo(()=>new Map(instructors.map(x=>[x.AdInstructorId,x])),[instructors]),courseById=useMemo(()=>new Map(courses.map(x=>[x.AdCourseId,x])),[courses]),collegeById=useMemo(()=>new Map(colleges.map(x=>[x.AdCollegeId,x])),[colleges]),sectionById=useMemo(()=>new Map(sections.map(x=>[x.AdSectionId,x])),[sections]),termById=useMemo(()=>new Map(terms.map(x=>[x.AdTermId,x])),[terms]);
 const latestTermId=useMemo(()=>terms.reduce((max,t)=>Math.max(max,Number(t.AdTermId)||0),0),[terms]);
 const resetToCurrent=()=>setFilters(prev=>({...fresh(),collegeId:prev.collegeId,sectionId:prev.sectionId,termId:latestTermId}));
 const isInstructor=activeMode==="searchInstructor"||activeMode==="reportInstructor",isRoom=activeMode==="searchRoom"||activeMode==="reportRoom",isTime=activeMode==="searchTime"||activeMode==="reportTime",isRoomTime=activeMode==="searchRoomTime"||activeMode==="reportRoomTime",isAdvanced=activeMode==="searchAdvanced",isDepartment=activeMode==="reportDepartment";
 const buildResults=(f=filters,m=activeMode)=>{let r=[...all];if(f.collegeId)r=r.filter(s=>s.AdCollegeId===f.collegeId);if(f.sectionId)r=r.filter(s=>s.AdSectionId===f.sectionId);if(f.termId)r=r.filter(s=>s.AdTermId===f.termId);if(f.instructorId)r=r.filter(s=>s.AdInstructorId===f.instructorId);if(m!=="searchAdvanced"&&f.civil.trim())r=r.filter(s=>(instructorById.get(s.AdInstructorId)?.AdInstructorCivil||"").includes(f.civil.trim()));if(f.building)r=r.filter(s=>String(s.AdRoomCode||"").includes(f.building));if(f.hall)r=r.filter(s=>String(s.AdRoomHall||"").includes(f.hall));if(f.startTime&&f.endTime)r=r.filter(s=>(s.fstarttime<=f.startTime&&s.fendtime>=f.startTime)||(s.fstarttime<=f.endTime&&s.fendtime>=f.endTime));if(f.courseId)r=r.filter(s=>s.AdCourseId===f.courseId);if(f.courseCode.trim())r=r.filter(s=>(courseById.get(s.AdCourseId)?.CourseCode||"")===f.courseCode.trim());const selectedDays=[f.sun,f.mon,f.tue,f.wed,f.thr].some(Boolean);if(selectedDays)r=r.filter(s=>(f.sun&&s.fsunday)||(f.mon&&s.fmonday)||(f.tue&&s.ftuesday)||(f.wed&&s.fwednesday)||(f.thr&&s.fthursday));return r};
 const apply=(e?:React.FormEvent)=>{e?.preventDefault();setResults(buildResults());setSearched(true);setPrintKind(null);setVisibleLimit(120)},set=(key:keyof Filters,value:any)=>setFilters(p=>({...p,[key]:value}));
 useEffect(()=>{if(!all.length)return;const raw=sessionStorage.getItem("schedule-report-prefill");if(!raw)return;try{const payload=JSON.parse(raw);if(!allowed.includes(payload?.mode as ReportMode))return;sessionStorage.removeItem("schedule-report-prefill");const next={...fresh(),...payload};setActiveMode(payload.mode);setFilters(next);setResults(buildResults(next,payload.mode));setSearched(true)}catch{sessionStorage.removeItem("schedule-report-prefill")}},[all]);
 const query=()=>{const q=new URLSearchParams();if(filters.termId)q.set("termId",String(filters.termId));if(filters.collegeId)q.set("collegeId",String(filters.collegeId));if(filters.sectionId)q.set("sectionId",String(filters.sectionId));if(filters.instructorId)q.set("instructorId",String(filters.instructorId));if(filters.building)q.set("building",filters.building);if(filters.hall)q.set("hall",filters.hall);return q.toString()},excel=(type:string)=>{window.location.href=`/api/reports/excel/${type}?${query()}`},printWhenReady=()=>requestAnimationFrame(()=>requestAnimationFrame(()=>window.print())),print=(pk:Exclude<PrintKind,null>)=>{setResults(buildResults());setPrintKind(pk);printWhenReady()};
 const CollegeField=()=> scopeState.lockCollege?null:<Field label="الكلية"><select value={filters.collegeId||""} onChange={e=>{const id=Number(e.target.value)||0;set("collegeId",id);set("sectionId",isPowerAdmin?(sections.find(sec=>sec.AdCollegeId===id)?.AdSectionId||0):(resolveScopeSelection(scopes,id,false).defaultSectionId||0))}}><option value="">الكل ...</option>{colleges.map(c=><option key={c.AdCollegeId} value={c.AdCollegeId}>{c.AdCollegeName}</option>)}</select></Field>;
 const SectionField=()=> scopeState.lockSection?null:<Field label="القسم العلمي"><select value={filters.sectionId||""} disabled={!filters.collegeId} onChange={e=>set("sectionId",Number(e.target.value)||0)}><option value="">الكل ...</option>{sectionOptions.map(s=><option key={s.AdSectionId} value={s.AdSectionId}>{s.AdSectionName}</option>)}</select></Field>;
 const TermField=()=> <Field label="الفصل الدراسي"><select value={filters.termId||""} onChange={e=>set("termId",Number(e.target.value)||latestTermId)}><option value="">الأحدث تلقائياً</option>{terms.map(t=><option key={t.AdTermId} value={t.AdTermId}>{t.AdTermName}</option>)}</select></Field>;
 const RoomFields=()=> <><Field label="المبنى"><select value={filters.building} onChange={e=>{set("building",e.target.value);set("hall","")}}><option value="">الكل ...</option>{buildings.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="القاعة"><select value={filters.hall} onChange={e=>set("hall",e.target.value)}><option value="">الكل ...</option>{halls.map(v=><option key={v}>{v}</option>)}</select></Field></>;
 const TimeFields=()=> <Field label="الفترة"><div className="time-pair"><input type="time" value={filters.startTime} onChange={e=>set("startTime",e.target.value)} aria-label="بداية الوقت"/><input type="time" value={filters.endTime} onChange={e=>set("endTime",e.target.value)} aria-label="نهاية الوقت"/></div></Field>;
 const filterFields=()=>{if(isDepartment)return <><CollegeField/><SectionField/><TermField/></>;if(isInstructor)return <><Field label="أستاذ المقرر"><select value={filters.instructorId||""} onChange={e=>set("instructorId",Number(e.target.value)||0)}><option value="">الكل ...</option>{instructors.map(i=><option key={i.AdInstructorId} value={i.AdInstructorId}>{i.AdInstructorName}</option>)}</select></Field><Field label="الرقم المدني"><input value={filters.civil} inputMode="numeric" onChange={e=>set("civil",e.target.value.replace(/\D/g,""))}/></Field><TermField/></>;if(isRoom)return <><CollegeField/><SectionField/><TermField/><RoomFields/></>;if(isTime)return <><CollegeField/><SectionField/><TimeFields/><TermField/></>;if(isRoomTime)return <><CollegeField/><SectionField/><TermField/><RoomFields/><TimeFields/></>;if(isAdvanced)return <><CollegeField/><SectionField/><TermField/><RoomFields/><Field label="أستاذ المقرر"><select value={filters.instructorId||""} onChange={e=>set("instructorId",Number(e.target.value)||0)}><option value="">الكل ...</option>{instructors.map(i=><option key={i.AdInstructorId} value={i.AdInstructorId}>{i.AdInstructorName}</option>)}</select></Field><Field label="المقرر"><select value={filters.courseId||""} onChange={e=>set("courseId",Number(e.target.value)||0)}><option value="">الكل ...</option>{courseOptions.map(c=><option key={c.AdCourseId} value={c.AdCourseId}>{c.CourseName}</option>)}</select></Field><Field label="رمز المقرر"><select value={filters.courseCode} onChange={e=>set("courseCode",e.target.value)}><option value="">الكل ...</option>{courseOptions.map(c=><option key={c.AdCourseId} value={c.CourseCode}>{c.CourseCode}</option>)}</select></Field><TimeFields/><Field label="الأيام"><div className="checkbox-row">{([['sun','الأحد'],['mon','الاثنين'],['tue','الثلاثاء'],['wed','الأربعاء'],['thr','الخميس']] as const).map(([k,l])=><label key={k}><input type="checkbox" checked={filters[k]} onChange={e=>set(k,e.target.checked)}/>{l}</label>)}</div></Field></>;return null};
 const activeChips=[filters.termId&&termById.get(filters.termId)?.AdTermName,filters.collegeId&&collegeById.get(filters.collegeId)?.AdCollegeName,filters.sectionId&&sectionById.get(filters.sectionId)?.AdSectionName,filters.instructorId&&instructorById.get(filters.instructorId)?.AdInstructorName,filters.building&&`مبنى ${filters.building}`,filters.hall&&`قاعة ${filters.hall}`,filters.startTime&&filters.endTime&&`${filters.startTime}–${filters.endTime}`].filter(Boolean) as string[];
 const filterChips=[filters.instructorId&&instructorById.get(filters.instructorId)?.AdInstructorName,filters.building&&`مبنى ${filters.building}`,filters.hall&&`قاعة ${filters.hall}`,filters.startTime&&filters.endTime&&`${filters.startTime}–${filters.endTime}`,filters.courseId&&courseById.get(filters.courseId)?.CourseName,filters.courseCode&&`رمز ${filters.courseCode}`].filter(Boolean) as string[];
 const liveReportResults=useMemo(()=>kind==="report"?buildResults():[],[kind,activeMode,all,filters,instructorById,courseById]);
 const printSearchResults=()=>{setResults(buildResults());setPrintKind("DepartmentSchedule");printWhenReady()};
 const exportSearchResults=()=>excel("ScheduleExcel");
 const ReportActions=()=>activeMode==="reportDepartment"?<><PrimaryButton type="button" onClick={()=>print("DepartmentSchedule")}><Printer/>تقرير القسم</PrimaryButton><SecondaryButton type="button" onClick={()=>print("ListofTeacherCourse")}><Printer/>كشف المزاولة</SecondaryButton><SecondaryButton type="button" onClick={()=>excel("ListofTeacherCourseExcel")}><Download/>Excel المزاولة</SecondaryButton><SecondaryButton type="button" onClick={()=>print("InstructorWithRoom")}><Printer/>الأساتذة مفصل</SecondaryButton></>:activeMode==="reportInstructor"?<><PrimaryButton type="button" onClick={()=>print("TeacherWithCourse")}><Printer/>استمارة المزاولة</PrimaryButton><SecondaryButton type="button" onClick={()=>print("InstructorReport2")}><Printer/>تقرير الأستاذ</SecondaryButton><SecondaryButton type="button" onClick={()=>excel("TeacherWithCourseExcel")}><Download/>Excel</SecondaryButton></>:activeMode==="reportRoom"?<>{user&&[1,34,35].includes(user.SystemUserId)?<SecondaryButton type="button" onClick={()=>print("WeekWithInstructor")}><Printer/>توفر القاعات · الجميع</SecondaryButton>:null}<PrimaryButton type="button" onClick={()=>print("RoomReport2")}><Printer/>تقرير القاعات</PrimaryButton><SecondaryButton type="button" onClick={()=>print("WeekWithInstructorByDept")}><Printer/>توفر القاعات · القسم</SecondaryButton></>:activeMode==="reportTime"?<PrimaryButton type="button" onClick={()=>print("TimeReport2")}><Printer/>طباعة تقرير الوقت</PrimaryButton>:<PrimaryButton type="button" onClick={()=>print("RoomTimeReport2")}><Printer/>طباعة وقت + قاعة</PrimaryButton>;
 const ResultCards=()=>{
  if(!results.length)return <EmptyState title="لا توجد نتائج مطابقة" detail="خفف بعض المعايير أو جرّب استعلاماً آخر."/>;
  return <RecordDeck className="query-results-deck">{results.slice(0,visibleLimit).map(s=>{
   const c=courseById.get(s.AdCourseId),ins=instructorById.get(s.AdInstructorId);
   return <RecordCard key={s.id} icon={<GraduationCap/>} title={c?.CourseName||s.AdCourseName||"مقرر"} subtitle={<><span>{c?.CourseCode||"—"} · شعبة {s.SCode}</span><span className="record-path"><UserRound/>{ins?.AdInstructorName||"بدون أستاذ"}</span></>} meta={<><MetaPill label="الوقت" value={`${s.fstarttime}–${s.fendtime}`} dir="ltr"/><MetaPill label="الأيام" value={dayText(s)||"—"}/><MetaPill label="المكان" value={`${s.AdRoomCode||"—"}/${s.AdRoomHall||"—"}`}/></>}/>;
  })}</RecordDeck>;
 };
 const reportFocusMatch=(s:FSchedule)=>!reportFocus||reportFocus.kind==="instructor"?(!reportFocus||String(s.AdInstructorId)===reportFocus.value):`${s.AdRoomCode}|${s.AdRoomHall}`===reportFocus.value;
 const ReportPreview=()=>{
  const focusMatches=reportFocus?liveReportResults.filter(reportFocusMatch):[];
  const preview=reportFocus?[...focusMatches,...liveReportResults.filter(s=>!reportFocusMatch(s)).slice(0,12)]:liveReportResults.slice(0,24);
  return <div className="report-paper" aria-label="معاينة التقرير"><header className="report-paper-head"><div><span>SCHEDULE</span><h2>{info.title}</h2><p>{activeChips.length?activeChips.join(" · "):"جميع البيانات المتاحة ضمن صلاحياتك"}</p></div><div><small>عدد السجلات</small><strong>{liveReportResults.length.toLocaleString("ar-KW-u-nu-latn")}</strong></div></header><div className="report-paper-rule"/><section className="report-paper-summary"><span>{termById.get(filters.termId)?.AdTermName||"كل الفصول"}</span><span>{sectionById.get(filters.sectionId)?.AdSectionName||collegeById.get(filters.collegeId)?.AdCollegeName||"النطاق المتاح"}</span><span>{new Date().toLocaleDateString("ar-KW-u-nu-latn")}</span></section><div className="report-paper-table"><div className="report-paper-row head"><span>المقرر</span><span>الشعبة</span><span>الأستاذ</span><span>الوقت</span><span>المكان</span></div>{preview.length?preview.map(s=>{const c=courseById.get(s.AdCourseId),ins=instructorById.get(s.AdInstructorId);return <div className={`report-paper-row ${reportFocus?(reportFocusMatch(s)?"living-match":"living-dim"):""}`} key={s.id}><span><b>{c?.CourseCode||"—"}</b><small>{c?.CourseName||s.AdCourseName||"مقرر"}</small></span><span>{s.SCode||"—"}</span><button type="button" className="living-cell" title="إبراز كل صفوف هذا الأستاذ" onClick={()=>runVisualTransition(()=>setReportFocus({kind:"instructor",value:String(s.AdInstructorId),label:ins?.AdInstructorName||"الأستاذ"}))}>{ins?.AdInstructorName||"—"}</button><span dir="ltr">{s.fstarttime}–{s.fendtime}</span><button type="button" className="living-cell" title="إبراز كل صفوف هذه القاعة" onClick={()=>runVisualTransition(()=>setReportFocus({kind:"room",value:`${s.AdRoomCode}|${s.AdRoomHall}`,label:`${s.AdRoomCode||"—"}/${s.AdRoomHall||"—"}`}))}>{s.AdRoomCode||"—"}/{s.AdRoomHall||"—"}</button></div>}):<div className="report-paper-empty">لا توجد سجلات مطابقة لهذه المعايير.</div>}</div>{reportFocus?<footer className="report-paper-more">تقرير حي · {focusMatches.length.toLocaleString("ar-KW-u-nu-latn")} صف مرتبط ظاهر بالكامل</footer>:liveReportResults.length>preview.length?<footer className="report-paper-more">+ {(liveReportResults.length-preview.length).toLocaleString("ar-KW-u-nu-latn")} سجل آخر في التقرير الكامل</footer>:<footer className="report-paper-more">معاينة حيّة · تتحدث تلقائياً مع الفلاتر</footer>}</div>
 };
 const PrintTable=()=>{if(!printKind)return null;const title:Record<Exclude<PrintKind,null>,string>={DepartmentSchedule:"تقرير القسم العلمي الشامل",ListofTeacherCourse:"كشف المزاولة",InstructorWithRoom:"تقرير الأساتذة مفصل",TeacherWithCourse:"طباعة استمارة المزاولة",InstructorReport2:"طباعة تقرير الأستاذ",WeekWithInstructor:"تقرير توفر القاعات للمبنى لجميع الأقسام",RoomReport2:"تقرير المباني والقاعات",WeekWithInstructorByDept:"تقرير توفر القاعات للمبنى للقسم",TimeReport2:"تقرير الوقت",RoomTimeReport2:"تقرير الوقت - المباني - القاعات"};if(printKind==="WeekWithInstructor"||printKind==="WeekWithInstructorByDept")return <div className="print-report"><h1>{title[printKind]}</h1><table><thead><tr><th>اليوم</th><th>الوقت</th><th>القاعة</th></tr></thead><tbody>{results.map(s=><tr key={s.id}><td>{dayText(s)}</td><td dir="ltr">{s.fstarttime} - {s.fendtime}</td><td>{s.AdRoomHall}</td></tr>)}</tbody></table></div>;if(printKind==="ListofTeacherCourse"||printKind==="TeacherWithCourse")return <div className="print-report"><h1>{title[printKind]}</h1><table><thead><tr><th>م</th><th>الاسم</th><th>الرقم المدني</th><th>المقرر الدراسي</th><th>رمز المقرر</th><th>الوقت</th><th>الأيام</th><th>الوحدات</th></tr></thead><tbody>{results.map((s,i)=>{const ins=instructorById.get(s.AdInstructorId),c=courseById.get(s.AdCourseId);return <tr key={s.id}><td>{i+1}</td><td>{ins?.AdInstructorName||""}</td><td>{ins?.AdInstructorCivil||""}</td><td>{c?.CourseName||s.AdCourseName||""}</td><td>{c?.CourseCode||""}</td><td dir="ltr">{s.fstarttime}-{s.fendtime}</td><td>{dayText(s)}</td><td>{c?.CourseCredit??""}</td></tr>})}</tbody></table></div>;return <div className="print-report"><h1>{title[printKind]}</h1><table><thead><tr>{["م","رمز المقرر","الشعبة","المقرر","الوحدات","الساعات","السعة","الوقت","الأيام","المبنى","القاعة","أستاذ المقرر","الرقم المدني"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{results.map((s,i)=>{const ins=instructorById.get(s.AdInstructorId),c=courseById.get(s.AdCourseId);return <tr key={s.id}><td>{i+1}</td><td>{c?.CourseCode||""}</td><td>{s.SCode}</td><td>{c?.CourseName||s.AdCourseName||""}</td><td>{c?.CourseCredit??""}</td><td>{c?.CourseHours??""}</td><td>{c?.MaxStudent??""}</td><td dir="ltr">{s.fstarttime}-{s.fendtime}</td><td>{dayText(s)}</td><td>{s.AdRoomCode}</td><td>{s.AdRoomHall}</td><td>{ins?.AdInstructorName||""}</td><td>{ins?.AdInstructorCivil||""}</td></tr>})}</tbody></table></div>};
 return <div className={`content-stack reports-page unified-workspace ${kind==="report"?"report-studio-page":"query-studio-page"}`}>
  <PageTitle eyebrow="الاستعلامات والتقارير" subtitle="ابحث أولاً، ثم اطبع أو صدّر النتيجة من نفس الشاشة دون التنقل بين شاشتين.">مركز الاستعلام والتقرير</PageTitle>
  {error?<Notice>{error}</Notice>:null}
  <section className="unified-mode-strip no-print"><span>اختر ما تريد</span><div>{allowed.map(m=><button key={m} type="button" className={activeMode===m?"active":""} onClick={()=>runVisualTransition(()=>{setActiveMode(m);setSearched(false);setPrintKind(null);setReportFocus(null)})}>{config[m].icon}<b>{config[m].short}</b></button>)}</div></section>
  {kind==="search"?<>
   <section className="query-workbench"><div className="smart-query-head"><div><span className="surface-kicker">{info.title}</span><h2>اكتب ما تعرفه فقط</h2></div><SlidersHorizontal/></div><form className="smart-filter-grid" onSubmit={apply}>{filterFields()}<div className="smart-filter-action"><PrimaryButton type="submit"><FileSearch/>تنفيذ الاستعلام</PrimaryButton></div></form>{filterChips.length?<div className="active-filter-chips">{filterChips.map(x=><span key={x}>{x}</span>)}<button type="button" onClick={()=>{resetToCurrent();setSearched(false)}}>مسح المرشحات</button></div>:null}</section>
   {searched?<section className="query-results clean-results"><div className="results-head"><div><span className="surface-kicker">النتيجة</span><strong>{results.length.toLocaleString("ar-KW-u-nu-latn")} موعد مطابق</strong></div><div className="query-result-actions no-print"><SecondaryButton type="button" onClick={printSearchResults}><Printer/>طباعة</SecondaryButton><SecondaryButton type="button" onClick={exportSearchResults}><Download/>Excel</SecondaryButton><Badge tone={results.length?"success":"neutral"}>{info.short}</Badge></div></div><ResultCards/>{results.length>visibleLimit?<div className="agenda-more"><SecondaryButton onClick={()=>setVisibleLimit(v=>v+120)}>عرض المزيد</SecondaryButton></div>:null}</section>:<section className="query-empty clean-empty"><EmptyState title="جاهز للاستعلام" detail="اختر نوع الاستعلام، أدخل المعلومة التي تعرفها، ثم نفّذ. لا حاجة لملء الحقول كلها."/></section>}
  </>:<div className="report-studio-layout">
   <aside className="report-studio-controls no-print"><section className="report-filter-inspector"><div className="smart-query-head"><div><span className="surface-kicker">{info.title}</span><h2>نطاق التقرير</h2></div><SlidersHorizontal/></div><form className="report-filter-form">{filterFields()}<div className="report-action-stack"><ReportActions/></div></form>{filterChips.length?<div className="active-filter-chips">{filterChips.map(x=><span key={x}>{x}</span>)}<button type="button" onClick={resetToCurrent}>مسح المرشحات</button></div>:null}</section></aside>
   <main className="report-preview-stage"><div className="report-preview-toolbar no-print"><span><b>{reportFocus?`تقرير حي · ${reportFocus.label}`:"معاينة حيّة"}</b><small>{reportFocus?"تم إبراز كل الصفوف المرتبطة — اضغط اسماً أو قاعة أخرى لتغيير العدسة":"اضغط اسم أستاذ أو قاعة داخل الورقة لإبراز كل العلاقات فوراً"}</small></span><div className="living-report-tools">{reportFocus?<button type="button" onClick={()=>runVisualTransition(()=>setReportFocus(null))}>إلغاء الإبراز</button>:null}<Badge tone={liveReportResults.length?"success":"neutral"}>{liveReportResults.length.toLocaleString("ar-KW-u-nu-latn")} سجل</Badge></div></div><ReportPreview/></main>
  </div>}
  <div className="print-only"><PrintTable/></div>
 </div>;
}
