import React from "react";
import { runVisualTransition } from "../utils/visualTransition";
import { AlertTriangle, Check, Edit2, Plus, Search, Trash2, X, Inbox, ChevronLeft } from "lucide-react";

export function PageTitle({ children, action, subtitle, eyebrow }: { children: React.ReactNode; action?: React.ReactNode; subtitle?: React.ReactNode; eyebrow?: React.ReactNode }) {
  return <div className="page-heading"><div className="page-heading-copy">{eyebrow ? <div className="page-eyebrow">{eyebrow}</div> : null}<h1>{children}</h1>{subtitle ? <p>{subtitle}</p> : null}</div>{action ? <div className="page-heading-action">{action}</div> : null}</div>;
}
export function Surface({ children, className = "" }: { children?: React.ReactNode; className?: string }) { return <section className={`surface ${className}`.trim()}>{children}</section>; }
export function Notice({ type = "error", children }: { type?: "error" | "success"; children: React.ReactNode }) { return <div className={`notice notice-${type}`} role={type === "error" ? "alert" : "status"}>{type === "error" ? <AlertTriangle aria-hidden="true" /> : <Check aria-hidden="true" />}<span>{children}</span></div>; }
export function PrimaryButton({ children, className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`btn btn-primary ${className}`.trim()}>{children}</button>; }
export function SecondaryButton({ children, className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`btn btn-secondary ${className}`.trim()}>{children}</button>; }
export function GhostButton({ children, className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button {...props} className={`btn btn-ghost ${className}`.trim()}>{children}</button>; }
export function AddButton({ children, onClick }: { children: React.ReactNode; onClick: () => void }) { return <PrimaryButton onClick={onClick}><Plus aria-hidden="true" />{children}</PrimaryButton>; }
export function IconAction({ label, kind, onClick }: { label: string; kind: "edit" | "delete"; onClick: () => void }) { return <button className={`icon-action icon-action-${kind}`} type="button" title={label} aria-label={label} onClick={onClick}>{kind === "edit" ? <Edit2 aria-hidden="true" /> : <Trash2 aria-hidden="true" />}</button>; }
export function Field({ label, required, children, hint }: { label: React.ReactNode; required?: boolean; children: React.ReactNode; hint?: React.ReactNode }) { return <div className="field"><label>{label}{required ? <span className="required">*</span> : null}</label>{children}{hint ? <span className="field-help">{hint}</span> : null}</div>; }
export function FormActions({ onBack, loading, submitDisabled, submitLabel = "موافق" }: { onBack: () => void; loading?: boolean; submitDisabled?: boolean; submitLabel?: React.ReactNode }) { return <div className="form-actions"><PrimaryButton type="submit" disabled={loading || submitDisabled}>{submitLabel}</PrimaryButton><SecondaryButton type="button" onClick={onBack} disabled={loading}>تراجع</SecondaryButton></div>; }
export function EmptyRow({ colSpan, label = "لا توجد بيانات مطابقة" }: { colSpan: number; label?: string }) { return <tr><td className="empty-cell" colSpan={colSpan}><span>{label}</span></td></tr>; }
export function ListToolbar({ value, onChange, placeholder = "بحث داخل البيانات", count, children }: { value: string; onChange: (value: string) => void; placeholder?: string; count?: number; children?: React.ReactNode }) { return <div className="list-toolbar"><div className="list-search"><Search aria-hidden="true"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>{value?<button type="button" onClick={()=>onChange("")} aria-label="مسح"><X/></button>:null}</div><div className="list-toolbar-side">{typeof count === "number" ? <span className="count-chip">{count.toLocaleString("ar-KW-u-nu-latn")} سجل</span> : null}{children}</div></div>; }
export function StatCard({ label, value, detail, icon }: { label: React.ReactNode; value: React.ReactNode; detail?: React.ReactNode; icon?: React.ReactNode }) { return <article className="stat-card"><div className="stat-icon">{icon}</div><div><strong>{value}</strong><span>{label}</span>{detail ? <small>{detail}</small> : null}</div></article>; }
export function Segmented({ value, options, onChange }: { value: string; options: Array<{value:string;label:React.ReactNode}>; onChange:(value:string)=>void }) { return <div className="segmented">{options.map(option=><button key={option.value} type="button" className={value===option.value?"active":""} onClick={()=>runVisualTransition(()=>onChange(option.value))}>{option.label}</button>)}</div>; }
export function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: "neutral"|"success"|"warning"|"danger"|"info" }) { return <span className={`badge badge-${tone}`}>{children}</span>; }

export function EmptyState({ title="لا توجد بيانات", detail="جرّب تغيير البحث أو المعايير الحالية.", action }: { title?:React.ReactNode; detail?:React.ReactNode; action?:React.ReactNode }) {
  return <div className="empty-state"><span className="empty-state-icon"><Inbox/></span><strong>{title}</strong><p>{detail}</p>{action?<div>{action}</div>:null}</div>;
}
export function RecordDeck({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`record-deck ${className}`.trim()}>{children}</div>}
export function RecordCard({icon,title,subtitle,meta,actions,onClick,className="",children}:{key?:string|number;icon?:React.ReactNode;title:React.ReactNode;subtitle?:React.ReactNode;meta?:React.ReactNode;actions?:React.ReactNode;onClick?:()=>void;className?:string;children?:React.ReactNode}){
  const engage=()=>{if(onClick)runVisualTransition(onClick)};
  const activate=(e:any)=>{if(!onClick)return;if(e.key==="Enter"||e.key===" "){e.preventDefault();engage()}};
  return <article role={onClick?"button":undefined} tabIndex={onClick?0:undefined} onKeyDown={activate} onClick={onClick?engage:undefined} className={`record-card ${onClick?"record-card-clickable":""} ${className}`.trim()}><div className="record-card-lead">{icon?<span className="record-card-icon">{icon}</span>:null}<div className="record-card-copy"><strong>{title}</strong>{subtitle?<span>{subtitle}</span>:null}{meta?<div className="record-card-meta">{meta}</div>:null}</div></div>{children?<div className="record-card-body">{children}</div>:null}{actions?<div className="record-card-actions" onClick={(e:any)=>e.stopPropagation()}>{actions}</div>:onClick?<ChevronLeft className="record-card-arrow"/>:null}</article>;
}
export function MetaPill({label,value,dir}:{label:React.ReactNode;value:React.ReactNode;dir?:"ltr"|"rtl"}){return <span className="meta-pill" dir={dir}><small>{label}</small><b>{value}</b></span>}
export function SkeletonDeck({count=4}:{count?:number}){return <div className="record-deck skeleton-deck">{Array.from({length:count},(_,i)=><article className="record-card skeleton-card" key={i}><span/><div><i/><i/></div></article>)}</div>}
